/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy } from './blog-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-files-attributes-created-by';
import { BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './blog-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { BlogListResponseDataItemAttributesImageDataAttributesRelated } from './blog-list-response-data-item-attributes-image-data-attributes-related';
/**
 * 
 * @export
 * @interface BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
 */
export interface BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes {
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    alternativeText?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    caption?: string;
    /**
     * 
     * @type {number}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    height?: number;
    /**
     * 
     * @type {any}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    formats?: any;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    hash?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    ext?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    mime?: string;
    /**
     * 
     * @type {number}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    previewUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    provider?: string;
    /**
     * 
     * @type {any}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    providerMetadata?: any;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesRelated}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    related?: BlogListResponseDataItemAttributesImageDataAttributesRelated;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    folder?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    folderPath?: string;
    /**
     * 
     * @type {Date}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    createdBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    updatedBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
