/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseDataItem } from './blog-list-response-data-item';
import { BlogListResponseMeta } from './blog-list-response-meta';
/**
 * 
 * @export
 * @interface BlogListResponse
 */
export interface BlogListResponse {
    /**
     * 
     * @type {Array<BlogListResponseDataItem>}
     * @memberof BlogListResponse
     */
    data?: Array<BlogListResponseDataItem>;
    /**
     * 
     * @type {BlogListResponseMeta}
     * @memberof BlogListResponse
     */
    meta?: BlogListResponseMeta;
}
