/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseDataItemAttributesImageDataAttributesFolder } from './blog-list-response-data-item-attributes-image-data-attributes-folder';
import { BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './blog-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { BlogListResponseDataItemAttributesImageDataAttributesRelated } from './blog-list-response-data-item-attributes-image-data-attributes-related';
/**
 * 
 * @export
 * @interface BlogListResponseDataItemAttributesImageDataAttributes
 */
export interface BlogListResponseDataItemAttributesImageDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    alternativeText?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    caption?: string;
    /**
     * 
     * @type {number}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    height?: number;
    /**
     * 
     * @type {any}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    formats?: any;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    hash?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    ext?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    mime?: string;
    /**
     * 
     * @type {number}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    previewUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    provider?: string;
    /**
     * 
     * @type {any}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    providerMetadata?: any;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesRelated}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    related?: BlogListResponseDataItemAttributesImageDataAttributesRelated;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolder}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    folder?: BlogListResponseDataItemAttributesImageDataAttributesFolder;
    /**
     * 
     * @type {string}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    folderPath?: string;
    /**
     * 
     * @type {Date}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    createdBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof BlogListResponseDataItemAttributesImageDataAttributes
     */
    updatedBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
