/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BlogRequestData
 */
export interface BlogRequestData {
    /**
     * 
     * @type {string}
     * @memberof BlogRequestData
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof BlogRequestData
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof BlogRequestData
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof BlogRequestData
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof BlogRequestData
     */
    tag?: string;
    /**
     * 
     * @type {number | string}
     * @memberof BlogRequestData
     */
    image?: number | string;
    /**
     * 
     * @type {string}
     * @memberof BlogRequestData
     */
    slug?: string;
}
