/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CalendarEventListResponseDataItemAttributes } from './calendar-event-list-response-data-item-attributes';
/**
 * 
 * @export
 * @interface CalendarEventResponseDataObject
 */
export interface CalendarEventResponseDataObject {
    /**
     * 
     * @type {number}
     * @memberof CalendarEventResponseDataObject
     */
    id?: number;
    /**
     * 
     * @type {CalendarEventListResponseDataItemAttributes}
     * @memberof CalendarEventResponseDataObject
     */
    attributes?: CalendarEventListResponseDataItemAttributes;
}
