/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CalendarResponseDataObjectAttributes } from './calendar-response-data-object-attributes';
/**
 * 
 * @export
 * @interface CalendarResponseDataObject
 */
export interface CalendarResponseDataObject {
    /**
     * 
     * @type {number}
     * @memberof CalendarResponseDataObject
     */
    id?: number;
    /**
     * 
     * @type {CalendarResponseDataObjectAttributes}
     * @memberof CalendarResponseDataObject
     */
    attributes?: CalendarResponseDataObjectAttributes;
}
