/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CalendarEventRequestData } from './calendar-event-request-data';
/**
 * 
 * @export
 * @interface CalendarEventRequest
 */
export interface CalendarEventRequest {
    /**
     * 
     * @type {CalendarEventRequestData}
     * @memberof CalendarEventRequest
     */
    data: CalendarEventRequestData;
}
