/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CandidateResidentVoteListResponseDataItemAttributesCandidateResidentData } from './candidate-resident-vote-list-response-data-item-attributes-candidate-resident-data';
/**
 * 
 * @export
 * @interface CandidateResidentVoteListResponseDataItemAttributesCandidateResident
 */
export interface CandidateResidentVoteListResponseDataItemAttributesCandidateResident {
    /**
     * 
     * @type {CandidateResidentVoteListResponseDataItemAttributesCandidateResidentData}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesCandidateResident
     */
    data?: CandidateResidentVoteListResponseDataItemAttributesCandidateResidentData;
}
