/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './blog-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { BlogListResponseDataItemAttributesImageDataAttributesRelated } from './blog-list-response-data-item-attributes-image-data-attributes-related';
import { CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissions } from './candidate-resident-vote-list-response-data-item-attributes-users-permissions-user-data-attributes-role-data-attributes-permissions';
/**
 * 
 * @export
 * @interface CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
 */
export interface CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    type?: string;
    /**
     * 
     * @type {CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissions}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    permissions?: CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissions;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesRelated}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    users?: BlogListResponseDataItemAttributesImageDataAttributesRelated;
    /**
     * 
     * @type {Date}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    createdBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributes
     */
    updatedBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
