/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseMeta } from './blog-list-response-meta';
import { CandidateResidentVoteListResponseDataItem } from './candidate-resident-vote-list-response-data-item';
/**
 * 
 * @export
 * @interface CandidateResidentVoteListResponse
 */
export interface CandidateResidentVoteListResponse {
    /**
     * 
     * @type {Array<CandidateResidentVoteListResponseDataItem>}
     * @memberof CandidateResidentVoteListResponse
     */
    data?: Array<CandidateResidentVoteListResponseDataItem>;
    /**
     * 
     * @type {BlogListResponseMeta}
     * @memberof CandidateResidentVoteListResponse
     */
    meta?: BlogListResponseMeta;
}
