/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CandidateResidentRequestData
 */
export interface CandidateResidentRequestData {
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentRequestData
     */
    details: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentRequestData
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentRequestData
     */
    dateApplied?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentRequestData
     */
    mixURL?: string;
    /**
     * 
     * @type {number | string}
     * @memberof CandidateResidentRequestData
     */
    mixFile?: number | string;
}
