/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CandidateResidentVoteListResponseDataItemAttributes } from './candidate-resident-vote-list-response-data-item-attributes';
/**
 * 
 * @export
 * @interface CandidateResidentVoteListResponseDataItemLocalized
 */
export interface CandidateResidentVoteListResponseDataItemLocalized {
    /**
     * 
     * @type {number}
     * @memberof CandidateResidentVoteListResponseDataItemLocalized
     */
    id?: number;
    /**
     * 
     * @type {CandidateResidentVoteListResponseDataItemAttributes}
     * @memberof CandidateResidentVoteListResponseDataItemLocalized
     */
    attributes?: CandidateResidentVoteListResponseDataItemAttributes;
}
