/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './blog-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRole } from './candidate-resident-vote-list-response-data-item-attributes-users-permissions-user-data-attributes-role';
import { CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesShows } from './candidate-resident-vote-list-response-data-item-attributes-users-permissions-user-data-attributes-shows';
/**
 * 
 * @export
 * @interface CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
 */
export interface CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    resetPasswordToken?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    confirmationToken?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    confirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    blocked?: boolean;
    /**
     * 
     * @type {CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRole}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    role?: CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRole;
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    phone?: string;
    /**
     * 
     * @type {CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesShows}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    shows?: CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesShows;
    /**
     * 
     * @type {Date}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    createdBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributes
     */
    updatedBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
