/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsAttributes } from './candidate-resident-vote-list-response-data-item-attributes-users-permissions-user-data-attributes-role-data-attributes-permissions-attributes';
/**
 * 
 * @export
 * @interface CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsData
 */
export interface CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsData {
    /**
     * 
     * @type {number}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsData
     */
    id?: number;
    /**
     * 
     * @type {CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsAttributes}
     * @memberof CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsData
     */
    attributes?: CandidateResidentVoteListResponseDataItemAttributesUsersPermissionsUserDataAttributesRoleDataAttributesPermissionsAttributes;
}
