/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CandidateResidentVoteRequestData
 */
export interface CandidateResidentVoteRequestData {
    /**
     * 
     * @type {number | string}
     * @memberof CandidateResidentVoteRequestData
     */
    candidateResident?: number | string;
    /**
     * 
     * @type {string}
     * @memberof CandidateResidentVoteRequestData
     */
    comment?: string;
    /**
     * 
     * @type {number | string}
     * @memberof CandidateResidentVoteRequestData
     */
    usersPermissionsUser?: number | string;
    /**
     * 
     * @type {boolean}
     * @memberof CandidateResidentVoteRequestData
     */
    approve: boolean;
}
