/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventItemResponseDataObject } from './event-item-response-data-object';
/**
 * 
 * @export
 * @interface EventItemResponse
 */
export interface EventItemResponse {
    /**
     * 
     * @type {EventItemResponseDataObject}
     * @memberof EventItemResponse
     */
    data?: EventItemResponseDataObject;
    /**
     * 
     * @type {any}
     * @memberof EventItemResponse
     */
    meta?: any;
}
