/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventItemListResponseDataItemAttributes } from './event-item-list-response-data-item-attributes';
/**
 * 
 * @export
 * @interface EventItemResponseDataObject
 */
export interface EventItemResponseDataObject {
    /**
     * 
     * @type {number}
     * @memberof EventItemResponseDataObject
     */
    id?: number;
    /**
     * 
     * @type {EventItemListResponseDataItemAttributes}
     * @memberof EventItemResponseDataObject
     */
    attributes?: EventItemListResponseDataItemAttributes;
}
