/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './blog-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { BlogListResponseDataItemAttributesImageDataAttributesRelated } from './blog-list-response-data-item-attributes-image-data-attributes-related';
import { EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributesPermissions } from './event-list-response-data-item-attributes-users-permissions-users-attributes-role-data-attributes-permissions';
/**
 * 
 * @export
 * @interface EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributes
 */
export interface EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributes
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributes
     */
    type?: string;
    /**
     * 
     * @type {EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributesPermissions}
     * @memberof EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributes
     */
    permissions?: EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributesPermissions;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesRelated}
     * @memberof EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributes
     */
    users?: BlogListResponseDataItemAttributesImageDataAttributesRelated;
    /**
     * 
     * @type {Date}
     * @memberof EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributes
     */
    createdBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributes
     */
    updatedBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
