/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseDataItemAttributesImage } from './blog-list-response-data-item-attributes-image';
import { BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './blog-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { BlogListResponseDataItemAttributesImageDataAttributesRelated } from './blog-list-response-data-item-attributes-image-data-attributes-related';
import { EventListResponseDataItemAttributesUsersPermissionsUsers } from './event-list-response-data-item-attributes-users-permissions-users';
/**
 * 
 * @export
 * @interface EventListResponseDataItemAttributes
 */
export interface EventListResponseDataItemAttributes {
    /**
     * 
     * @type {string}
     * @memberof EventListResponseDataItemAttributes
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof EventListResponseDataItemAttributes
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof EventListResponseDataItemAttributes
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof EventListResponseDataItemAttributes
     */
    promoter?: string;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImage}
     * @memberof EventListResponseDataItemAttributes
     */
    image?: BlogListResponseDataItemAttributesImage;
    /**
     * 
     * @type {string}
     * @memberof EventListResponseDataItemAttributes
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof EventListResponseDataItemAttributes
     */
    slug?: string;
    /**
     * 
     * @type {EventListResponseDataItemAttributesUsersPermissionsUsers}
     * @memberof EventListResponseDataItemAttributes
     */
    usersPermissionsUsers?: EventListResponseDataItemAttributesUsersPermissionsUsers;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesRelated}
     * @memberof EventListResponseDataItemAttributes
     */
    shows?: BlogListResponseDataItemAttributesImageDataAttributesRelated;
    /**
     * 
     * @type {Date}
     * @memberof EventListResponseDataItemAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EventListResponseDataItemAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EventListResponseDataItemAttributes
     */
    publishedAt?: Date;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof EventListResponseDataItemAttributes
     */
    createdBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof EventListResponseDataItemAttributes
     */
    updatedBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
