/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributesPermissionsAttributes } from './event-list-response-data-item-attributes-users-permissions-users-attributes-role-data-attributes-permissions-attributes';
/**
 * 
 * @export
 * @interface EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributesPermissionsData
 */
export interface EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributesPermissionsData {
    /**
     * 
     * @type {number}
     * @memberof EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributesPermissionsData
     */
    id?: number;
    /**
     * 
     * @type {EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributesPermissionsAttributes}
     * @memberof EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributesPermissionsData
     */
    attributes?: EventListResponseDataItemAttributesUsersPermissionsUsersAttributesRoleDataAttributesPermissionsAttributes;
}
