/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseMeta } from './blog-list-response-meta';
import { EventListResponseDataItem } from './event-list-response-data-item';
/**
 * 
 * @export
 * @interface EventListResponse
 */
export interface EventListResponse {
    /**
     * 
     * @type {Array<EventListResponseDataItem>}
     * @memberof EventListResponse
     */
    data?: Array<EventListResponseDataItem>;
    /**
     * 
     * @type {BlogListResponseMeta}
     * @memberof EventListResponse
     */
    meta?: BlogListResponseMeta;
}
