/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventItemRequestData
 */
export interface EventItemRequestData {
    /**
     * 
     * @type {string}
     * @memberof EventItemRequestData
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EventItemRequestData
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof EventItemRequestData
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof EventItemRequestData
     */
    secureImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof EventItemRequestData
     */
    imagePublicId?: string;
    /**
     * 
     * @type {number | string}
     * @memberof EventItemRequestData
     */
    image?: number | string;
}
