/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LiveInfoRequestData
 */
export interface LiveInfoRequestData {
    /**
     * 
     * @type {any}
     * @memberof LiveInfoRequestData
     */
    current: any;
    /**
     * 
     * @type {any}
     * @memberof LiveInfoRequestData
     */
    next0?: any;
    /**
     * 
     * @type {any}
     * @memberof LiveInfoRequestData
     */
    next1?: any;
    /**
     * 
     * @type {any}
     * @memberof LiveInfoRequestData
     */
    next2?: any;
    /**
     * 
     * @type {any}
     * @memberof LiveInfoRequestData
     */
    next3?: any;
}
