/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MixListResponseDataItemAttributesShowDataAttributes } from './mix-list-response-data-item-attributes-show-data-attributes';
/**
 * 
 * @export
 * @interface MixListResponseDataItemAttributesShowData
 */
export interface MixListResponseDataItemAttributesShowData {
    /**
     * 
     * @type {number}
     * @memberof MixListResponseDataItemAttributesShowData
     */
    id?: number;
    /**
     * 
     * @type {MixListResponseDataItemAttributesShowDataAttributes}
     * @memberof MixListResponseDataItemAttributesShowData
     */
    attributes?: MixListResponseDataItemAttributesShowDataAttributes;
}
