/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MixListResponseDataItemAttributesShowDataAttributesUsersAttributes } from './mix-list-response-data-item-attributes-show-data-attributes-users-attributes';
/**
 * 
 * @export
 * @interface MixListResponseDataItemAttributesShowDataAttributesUsersData
 */
export interface MixListResponseDataItemAttributesShowDataAttributesUsersData {
    /**
     * 
     * @type {number}
     * @memberof MixListResponseDataItemAttributesShowDataAttributesUsersData
     */
    id?: number;
    /**
     * 
     * @type {MixListResponseDataItemAttributesShowDataAttributesUsersAttributes}
     * @memberof MixListResponseDataItemAttributesShowDataAttributesUsersData
     */
    attributes?: MixListResponseDataItemAttributesShowDataAttributesUsersAttributes;
}
