/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseDataItemAttributesImage } from './blog-list-response-data-item-attributes-image';
import { BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './blog-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { MixListResponseDataItemAttributesShowDataAttributesUsers } from './mix-list-response-data-item-attributes-show-data-attributes-users';
/**
 * 
 * @export
 * @interface MixListResponseDataItemAttributesShowDataAttributes
 */
export interface MixListResponseDataItemAttributesShowDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    tagline?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    airtimeUsername?: string;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    airtimePassword?: string;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    instagram?: string;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    facebook?: string;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    twitter?: string;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    website?: string;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImage}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    image?: BlogListResponseDataItemAttributesImage;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    secureImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    imagePublicId?: string;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    imageOid?: string;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    mongoId?: string;
    /**
     * 
     * @type {MixListResponseDataItemAttributesShowDataAttributesUsers}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    users?: MixListResponseDataItemAttributesShowDataAttributesUsers;
    /**
     * 
     * @type {string}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    mixcloudPlaylist?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    alwaysUploadToMixcloud?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    createdBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof MixListResponseDataItemAttributesShowDataAttributes
     */
    updatedBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
