/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy } from './blog-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-files-attributes-created-by';
import { BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './blog-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { PageListResponseDataItemAttributesMedia } from './page-list-response-data-item-attributes-media';
/**
 * 
 * @export
 * @interface PageListResponseDataItemAttributes
 */
export interface PageListResponseDataItemAttributes {
    /**
     * 
     * @type {string}
     * @memberof PageListResponseDataItemAttributes
     */
    content?: string;
    /**
     * 
     * @type {PageListResponseDataItemAttributesMedia}
     * @memberof PageListResponseDataItemAttributes
     */
    media?: PageListResponseDataItemAttributesMedia;
    /**
     * 
     * @type {string}
     * @memberof PageListResponseDataItemAttributes
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof PageListResponseDataItemAttributes
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PageListResponseDataItemAttributes
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof PageListResponseDataItemAttributes
     */
    mongoId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PageListResponseDataItemAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PageListResponseDataItemAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PageListResponseDataItemAttributes
     */
    publishedAt?: Date;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy}
     * @memberof PageListResponseDataItemAttributes
     */
    createdBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesFilesAttributesCreatedBy;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof PageListResponseDataItemAttributes
     */
    updatedBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
