/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PatreonCacheListResponseDataItemAttributes } from './patreon-cache-list-response-data-item-attributes';
/**
 * 
 * @export
 * @interface PatreonCacheListResponseDataItemLocalized
 */
export interface PatreonCacheListResponseDataItemLocalized {
    /**
     * 
     * @type {number}
     * @memberof PatreonCacheListResponseDataItemLocalized
     */
    id?: number;
    /**
     * 
     * @type {PatreonCacheListResponseDataItemAttributes}
     * @memberof PatreonCacheListResponseDataItemLocalized
     */
    attributes?: PatreonCacheListResponseDataItemAttributes;
}
