/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PodcastRequestData
 */
export interface PodcastRequestData {
    /**
     * 
     * @type {string}
     * @memberof PodcastRequestData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PodcastRequestData
     */
    bio: string;
    /**
     * 
     * @type {string}
     * @memberof PodcastRequestData
     */
    mixcloud?: string;
    /**
     * 
     * @type {number | string}
     * @memberof PodcastRequestData
     */
    image?: number | string;
}
