/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PosterRequestData
 */
export interface PosterRequestData {
    /**
     * 
     * @type {string}
     * @memberof PosterRequestData
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof PosterRequestData
     */
    displayFrom: Date;
    /**
     * 
     * @type {Date}
     * @memberof PosterRequestData
     */
    displayUntil: Date;
    /**
     * 
     * @type {string}
     * @memberof PosterRequestData
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof PosterRequestData
     */
    active: string;
    /**
     * 
     * @type {number | string}
     * @memberof PosterRequestData
     */
    image?: number | string;
}
