/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RecordingRequestData
 */
export interface RecordingRequestData {
    /**
     * 
     * @type {string}
     * @memberof RecordingRequestData
     */
    episodeName: string;
    /**
     * 
     * @type {string}
     * @memberof RecordingRequestData
     */
    fileName: string;
    /**
     * 
     * @type {Date}
     * @memberof RecordingRequestData
     */
    recordingDate: Date;
    /**
     * 
     * @type {number}
     * @memberof RecordingRequestData
     */
    lengthSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof RecordingRequestData
     */
    fileSizeBytes?: string;
    /**
     * 
     * @type {number | string}
     * @memberof RecordingRequestData
     */
    mix?: number | string;
    /**
     * 
     * @type {number | string}
     * @memberof RecordingRequestData
     */
    show?: number | string;
    /**
     * 
     * @type {boolean}
     * @memberof RecordingRequestData
     */
    automaticallyRecorded: boolean;
    /**
     * 
     * @type {number | string}
     * @memberof RecordingRequestData
     */
    uploadedBy?: number | string;
    /**
     * 
     * @type {string}
     * @memberof RecordingRequestData
     */
    replacementFileName?: string;
}
