/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MixListResponseDataItemAttributes } from './mix-list-response-data-item-attributes';
/**
 * 
 * @export
 * @interface RecordingListResponseDataItemAttributesMixData
 */
export interface RecordingListResponseDataItemAttributesMixData {
    /**
     * 
     * @type {number}
     * @memberof RecordingListResponseDataItemAttributesMixData
     */
    id?: number;
    /**
     * 
     * @type {MixListResponseDataItemAttributes}
     * @memberof RecordingListResponseDataItemAttributesMixData
     */
    attributes?: MixListResponseDataItemAttributes;
}
