/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent } from './blog-list-response-data-item-attributes-image-data-attributes-folder-data-attributes-parent';
import { RecordingListResponseDataItemAttributesMix } from './recording-list-response-data-item-attributes-mix';
/**
 * 
 * @export
 * @interface RecordingListResponseDataItemAttributes
 */
export interface RecordingListResponseDataItemAttributes {
    /**
     * 
     * @type {string}
     * @memberof RecordingListResponseDataItemAttributes
     */
    episodeName?: string;
    /**
     * 
     * @type {string}
     * @memberof RecordingListResponseDataItemAttributes
     */
    fileName?: string;
    /**
     * 
     * @type {Date}
     * @memberof RecordingListResponseDataItemAttributes
     */
    recordingDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof RecordingListResponseDataItemAttributes
     */
    lengthSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof RecordingListResponseDataItemAttributes
     */
    fileSizeBytes?: string;
    /**
     * 
     * @type {RecordingListResponseDataItemAttributesMix}
     * @memberof RecordingListResponseDataItemAttributes
     */
    mix?: RecordingListResponseDataItemAttributesMix;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof RecordingListResponseDataItemAttributes
     */
    show?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {boolean}
     * @memberof RecordingListResponseDataItemAttributes
     */
    automaticallyRecorded?: boolean;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof RecordingListResponseDataItemAttributes
     */
    uploadedBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {string}
     * @memberof RecordingListResponseDataItemAttributes
     */
    replacementFileName?: string;
    /**
     * 
     * @type {Date}
     * @memberof RecordingListResponseDataItemAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RecordingListResponseDataItemAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof RecordingListResponseDataItemAttributes
     */
    createdBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent}
     * @memberof RecordingListResponseDataItemAttributes
     */
    updatedBy?: BlogListResponseDataItemAttributesImageDataAttributesFolderDataAttributesParent;
}
