/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SpecialRequestData
 */
export interface SpecialRequestData {
    /**
     * 
     * @type {string}
     * @memberof SpecialRequestData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SpecialRequestData
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof SpecialRequestData
     */
    tagline?: string;
    /**
     * 
     * @type {number | string}
     * @memberof SpecialRequestData
     */
    image?: number | string;
    /**
     * 
     * @type {string}
     * @memberof SpecialRequestData
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof SpecialRequestData
     */
    secureImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof SpecialRequestData
     */
    imagePublicId?: string;
    /**
     * 
     * @type {string}
     * @memberof SpecialRequestData
     */
    imageOid?: string;
    /**
     * 
     * @type {string}
     * @memberof SpecialRequestData
     */
    mongoId?: string;
}
