/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsersPermissionsRoleListResponseDataItemAttributesPermissionsAttributesRoleDataAttributesUsersAttributesShowsData } from './users-permissions-role-list-response-data-item-attributes-permissions-attributes-role-data-attributes-users-attributes-shows-data';
/**
 * 
 * @export
 * @interface UsersPermissionsRoleListResponseDataItemAttributesPermissionsAttributesRoleDataAttributesUsersAttributesShows
 */
export interface UsersPermissionsRoleListResponseDataItemAttributesPermissionsAttributesRoleDataAttributesUsersAttributesShows {
    /**
     * 
     * @type {Array<UsersPermissionsRoleListResponseDataItemAttributesPermissionsAttributesRoleDataAttributesUsersAttributesShowsData>}
     * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsAttributesRoleDataAttributesUsersAttributesShows
     */
    data?: Array<UsersPermissionsRoleListResponseDataItemAttributesPermissionsAttributesRoleDataAttributesUsersAttributesShowsData>;
}
